### ISSUE TITLE
for `fabric("character")`, can we hit OpeNDAP for last five steps?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#103]
For default populating `times` with a small subset of the data. 

@jiwalker-usgs had ideas on this. Do you remember how this would be done in R? @dblodgett-usgs?

**Comment by jread-usgs** [comment]
The idea is to just start the webdata object with a piece of the dataset, so the default isn't the entire time range.

**Comment by jiwalker-usgs** [comment]
This is somewhat complicated due to the flexible nature of netcdf/opendap.  If you have a dataset, you can look at its shape via:

http://cida.usgs.gov/thredds/dodsC/prism.dds

From here you see that there are several GRID types which all reference the lon, lat, time dimensions. The next step is to query the attributes via:

http://cida.usgs.gov/thredds/dodsC/prism.das

where you can see that these three variables have the units "degrees_east", "degrees_north", and "days since 1858-11-17 00:00:00" respectively.  If you use something like udunits to parse these units you will find that the third one is a time dimension (you probably figured that out already, but the computer hasn't).  Knowing this you can get the last 5 elements of the time variable via:

http://cida.usgs.gov/thredds/dodsC/prism.ascii?time[1413:1:1417]

This is the manual way to do it and depending on your language of choice there are probably good ways to go.  I haven't looked much at ncdf, but it probably has some nice functionality so you don't need to know OPeNDAP directly.

**Comment by dblodgett-usgs** [comment]
Good summary, @jiwalker-usgs, ncdf4 will treat OPeNDAP as if its a local NetCDF File so you can get all the content needed here as local R objects with some pretty simple calls. You then need to do all the units and date index conversions. [See this function](https://github.com/jjvanderwal/climates/blob/master/R/CF_date_range.R) for one approach that uses chron and julian.

**Comment by jread-usgs** [comment]
Thanks guys. I do something with GRID types already, and I think I can dig that up for the pattern. Thanks!

**Comment by jread-usgs** [comment]
@dblodgett-usgs didn't realize your solution was an ncdf4-only option...hoping to keep that package out of the dependencies unless it is reliably hosted. Will look into another way.

**Comment by dblodgett-usgs** [comment]
It's not ncdf4-only. To do it without a NetCDF dependency, you can:
* get attributes needed like: http://cida.usgs.gov/thredds/dodsC/prism.das
  * Look for something with units like "* since *"
  * That string is the time_units required by CF_date_range.
  * The variable associated with those units is what you want for the time_dim
* get time like: http://cida.usgs.gov/thredds/dodsC/prism.ascii?time
  * The values you get back from that are the time_dim values.

From there, you DO need chron and julian to convert the date units to/from date indices.
