### ISSUE TITLE
Possible to pass auth to be able to use private WFS?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/geoknife#127]
Guessing this is a no, but curious anyhow.

**Comment by jiwalker-usgs** [comment]
WFS doesn't have anything in the spec for access control, so it depends on what is making the WFS private (OAuth, Basic HTTP, etc).  Are we mainly thinking ScienceBase here? Because even after figuring that out, the client would have a hard time passing the credentials to the GDP to use within a reference.  It is possible, and we are talking about how to do this for OPeNDAP and OAuth.

**Comment by jread-usgs** [comment]
Yep, sciencebase. I don't think it is worth the effort at this point to support. private geospatial feature data might be a pretty small edge-case?

**Comment by aappling-usgs** [comment]
i agree - small edge case.

**Comment by jread-usgs** [comment]
Had a call about this today. We'll keep our ears open, but it looks like this is a long ways off.
