### ISSUE TITLE
move time limits from fabric to stencil?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/geoknife#160]
Doesn't seem like a big deal either way, but it could make sense from a user's perspective to have the time limits to an analysis be specified with the stencil rather than the fabric - if a stencil cuts in space, why not also in time?

**Comment by jread-usgs** [comment]
good question. I will think on it. that is a case where the metaphor might break down a bit. stencil itself is really supposed to be space only, but times might make more sense in `knife` than in `fabric`...

**Comment by jread-usgs** [comment]
@jiwalker-usgs  thoughts?

**Comment by jiwalker-usgs** [comment]
I agree that it should be taken out of ``fabric`` because that represents the whole dataset, which includes all timesteps.  I think putting it in ``knife`` makes sense from the GDP perspective because that is where it sits in the WPS request.  I do like the idea of having all dimensional parameters including time place in the ``stencil``.  A multidimensional ``stencil`` might be cool.  Not sure how it would break the API or fit with the WPS pattern though.

**Comment by jread-usgs** [comment]
doesn't the same logic apply to where `variables` is slotted?

**Comment by jread-usgs** [comment]
I think the ship has sailed on this one...but I do agree generally.
