### ISSUE TITLE
stencil from SpatialPolygons or SpatialPolygonsDataFrame

### ISSUE THREAD

**Issue by ghost** [USGS-R/geoknife#291]
Getting the following errors when passing a class SpatialPolygons or SpatialPolygonsDataFrame to simplegeom:

stencil <- simplegeom(a)
Error in as(.Object, "simplegeom") : 
  no method or default for coercing “SpatialPolygons” to “simplegeom”

stencil <- simplegeom(MSA)
Error in as(.Object, "simplegeom") : 
  no method or default for coercing “SpatialPolygonsDataFrame” to “simplegeom”

class(a)
[1] "SpatialPolygons"
attr(,"package")

class(MSA)
[1] "SpatialPolygonsDataFrame"
attr(,"package")
[1] "sp"

**Comment by jread-usgs** [comment]
@ghost sorry, just saw this. The method to coerce sp into a simplegeom is a bit of a mess - this is something that can be done with the existing package, but it isn't exposed because I don't yet have a good way to make sure the projections of the sp objects that exist can be handled by the processing. I would like to take care of this, just hadn't run into a user yet that needed it. what is the CRS you are using?

**Comment by jhollist** [comment]
@jread-usgs +1 on this!

**Comment by jread-usgs** [comment]
Yep, you got it Jeff, or I could support a few common ones with a look up and fail with a descriptive error when it isn't supported. That way people could easily PR a new proj

**Comment by jread-usgs** [comment]
Here is where the WGS84 is hardcoded in for `simplegeom`: https://github.com/USGS-R/geoknife/blob/7361b82d5ac0ec4f5ebb4c724143ebc1d18a427e/R/processInputsToXML.R#L200

I think we can work on the 
```r
setMethod("simplegeom", signature("Spatial"), function(.Object, ...) {
})
```
method so that this is intuitive.

**Comment by jread-usgs** [comment]
BTW, when this is implemented initially, it will only support `SpatialPolygons` or `SpatialPolygonsDataFrame` objects because `SpatialPoints` will need a little bit different treatment.

**Comment by jread-usgs** [comment]
This is implemented and on the current CRAN version. Feedback welcome.
