### ISSUE TITLE
Error accessing NLDAS:  HTTP/1.1 401 Unauthorized 

### ISSUE THREAD

**Issue by lerban** [USGS-R/geoknife#316]
Out of my depth on the following error when accessing NLDAS resource:

check(job)
$status
[1] "General Error: java.io.IOException: java.io.IOException: org.apache.commons.httpclient.auth.InvalidCredentialsException: HTTP/1.1 401 Unauthorized"

for fabric:
fabric = webdata('nldas', times = c("2000-01-01","2000-01-31"), variables = c("pevapsfc"))
> fabric
An object of class "webdata":
times: 2000-01-01T00:00:00Z, 2000-01-31T00:00:00Z
url: dods://hydro1.sci.gsfc.nasa.gov/dods/NLDAS_FORA0125_H.002 
variables: pevapsfc

**Comment by jread-usgs** [comment]
Sorry @lerban NASA has put an authorization token requirement on those services and we are now working on how to support that on our end. I think in the current CRAN version of `geoknife`, those `nldas` and `gldas` datasets were removed as quickaccess datasets (i.e., ones that you could just punch in the character name of the dataset) because of this. 

We hope to support this pattern in the future (accessing datasets that require authorization). But for now, I am sorry this doesn't work for you.

**Comment by lerban** [comment]
Ok, thanks for a quick reply!

**Comment by jread-usgs** [comment]
Closing this as a wontfix
